export const users = [
  {
    _id: '6595fff7c0d16c724e00691b',
    index: 0,
    guid: 'ef0a59b2-a61d-4cc1-988e-3371fed39877',
    isActive: false,
    balance: '$3,191.28',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'blue',
    name: 'Penelope Bray',
    gender: 'female',
    company: 'ZOLAVO',
    email: 'penelopebray@zolavo.com',
    phone: '+1 (846) 527-3363',
    address: '781 Berry Street, Hillsboro, Alaska, 9474',
    about:
      'Elit sit Lorem ad officia duis pariatur. Incididunt irure consectetur ut anim mollit. Aliqua ea minim eiusmod adipisicing cupidatat veniam aliquip in ad qui qui deserunt cupidatat. Elit excepteur irure eu aliquip consequat reprehenderit. Tempor ut in duis et ex excepteur dolore proident aliqua tempor.\r\n',
    registered: '2017-02-15T05:11:54 -02:00',
    latitude: 43.454878,
    longitude: -99.041801,
    tags: [
      'exercitation',
      'aliquip',
      'nostrud',
      'amet',
      'irure',
      'fugiat',
      'veniam',
    ],
    friends: [
      {
        id: 0,
        name: 'Vasquez Walls',
      },
      {
        id: 1,
        name: 'Sullivan Koch',
      },
      {
        id: 2,
        name: 'Guy Albert',
      },
    ],
    greeting: 'Hello, Penelope Bray! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6595fff7e865c96e74b32caf',
    index: 1,
    guid: '2570c005-7e1a-45b9-addf-73a757c8b6ac',
    isActive: true,
    balance: '$1,937.88',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'blue',
    name: 'Montoya Cash',
    gender: 'male',
    company: 'FUELWORKS',
    email: 'montoyacash@fuelworks.com',
    phone: '+1 (933) 428-2370',
    address: '843 Gem Street, Chesapeake, Wisconsin, 3441',
    about:
      'Anim aliquip duis sunt ex amet aute occaecat et elit cillum. Consectetur nisi ut duis ullamco quis elit aliqua magna quis duis. Sunt magna nulla ut amet elit qui aliqua. Magna anim anim consequat mollit voluptate reprehenderit irure culpa reprehenderit esse culpa et.\r\n',
    registered: '2022-09-27T09:03:55 -03:00',
    latitude: 86.836201,
    longitude: -160.038137,
    tags: ['velit', 'occaecat', 'sunt', 'Lorem', 'officia', 'sint', 'do'],
    friends: [
      {
        id: 0,
        name: 'Doris Nash',
      },
      {
        id: 1,
        name: 'Pollard Mcdowell',
      },
      {
        id: 2,
        name: 'Harper Strickland',
      },
    ],
    greeting: 'Hello, Montoya Cash! You have 9 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6595fff781dd1ecfef2294ec',
    index: 2,
    guid: 'ad1f1040-bee0-4046-8e4b-222bb7d292be',
    isActive: true,
    balance: '$3,496.43',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'blue',
    name: 'Mallory Morin',
    gender: 'female',
    company: 'EMERGENT',
    email: 'mallorymorin@emergent.com',
    phone: '+1 (865) 536-3560',
    address: '516 Ocean Court, Martinsville, Virgin Islands, 5266',
    about:
      'Cillum veniam reprehenderit amet deserunt ea ex. Eu esse pariatur duis esse cillum. Laborum fugiat dolor dolore amet adipisicing fugiat eiusmod tempor qui. Elit eiusmod proident dolore minim officia dolor.\r\n',
    registered: '2023-01-15T06:06:27 -02:00',
    latitude: -25.670179,
    longitude: 89.325028,
    tags: ['eiusmod', 'dolor', 'enim', 'enim', 'consectetur', 'cillum', 'duis'],
    friends: [
      {
        id: 0,
        name: 'Odessa Mitchell',
      },
      {
        id: 1,
        name: 'Rivers Caldwell',
      },
      {
        id: 2,
        name: 'Fields Mcknight',
      },
    ],
    greeting: 'Hello, Mallory Morin! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6595fff7931ab8c8e42b0d59',
    index: 3,
    guid: '9fb51e7c-542e-4aef-bb76-83a2d2ff6803',
    isActive: true,
    balance: '$2,260.66',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'green',
    name: 'Wong Allison',
    gender: 'male',
    company: 'WATERBABY',
    email: 'wongallison@waterbaby.com',
    phone: '+1 (904) 407-3037',
    address: '293 Fillmore Avenue, Balm, Indiana, 6682',
    about:
      'Consectetur excepteur anim veniam non. Irure deserunt voluptate et proident reprehenderit commodo elit excepteur esse excepteur reprehenderit. Qui dolore ea Lorem proident veniam consequat nisi quis cillum. Amet id in deserunt ex. Magna elit proident et occaecat occaecat ullamco. In veniam nisi aliqua esse sunt eu. Deserunt laborum sunt sit excepteur incididunt.\r\n',
    registered: '2018-03-14T04:08:59 -02:00',
    latitude: 12.289677,
    longitude: -136.523071,
    tags: [
      'mollit',
      'cillum',
      'incididunt',
      'excepteur',
      'laboris',
      'id',
      'do',
    ],
    friends: [
      {
        id: 0,
        name: 'Carla Cameron',
      },
      {
        id: 1,
        name: 'Marian Frederick',
      },
      {
        id: 2,
        name: 'Armstrong Clay',
      },
    ],
    greeting: 'Hello, Wong Allison! You have 9 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6595fff724f3cd43df5efd7e',
    index: 4,
    guid: '5bb9b252-3e79-4e8a-85ae-f06bf29f63d3',
    isActive: false,
    balance: '$1,254.44',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Klein Duncan',
    gender: 'male',
    company: 'KIGGLE',
    email: 'kleinduncan@kiggle.com',
    phone: '+1 (913) 472-2615',
    address: '316 Lester Court, Gibbsville, Hawaii, 7992',
    about:
      'Aliquip nisi aute deserunt quis occaecat est dolor incididunt. Qui eiusmod mollit commodo esse ut irure veniam in veniam et labore. Qui fugiat sunt anim amet ut laboris nisi qui voluptate dolore nulla elit fugiat excepteur. Aliquip id officia nostrud qui reprehenderit pariatur eu voluptate qui nulla est ullamco.\r\n',
    registered: '2017-03-18T06:11:00 -02:00',
    latitude: -51.30567,
    longitude: 144.644688,
    tags: [
      'dolore',
      'cupidatat',
      'et',
      'ea',
      'eiusmod',
      'voluptate',
      'laboris',
    ],
    friends: [
      {
        id: 0,
        name: 'Felicia Molina',
      },
      {
        id: 1,
        name: 'Randolph Wallace',
      },
      {
        id: 2,
        name: 'Holmes Garza',
      },
    ],
    greeting: 'Hello, Klein Duncan! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
];
